version: '2.1'
services:

  ldap:
    image: giafar/spid-ldap
    container_name: ldap.example.org
    build:
      context: ../ldap
    networks:
      shibboleth-net:
        ipv4_address: 172.20.0.2

  shibboleth-idp:
    image: giafar/spid-idp
    container_name: idp.example.org
    build:
      context: ../idp
    depends_on:
      - ldap
    links:
      - ldap:ldap.example.org
    networks:
      shibboleth-net:
        ipv4_address: 172.20.0.3
    volumes: 
      - idp_metadata:/opt/shibboleth-idp/sp-metadata

  shibboleth-sp:
    image: giafar/spid-sp
    container_name: sp.example.org
    build:
      context: ../sp
    depends_on:
      - shibboleth-idp
    links:
      - shibboleth-idp:idp.example.org
    networks:
      shibboleth-net:
        ipv4_address: 172.20.0.4

volumes:
  idp_metadata:

networks: 
  shibboleth-net:
    ipam:
      config:
        - subnet: 172.20.0.0/24        